server:
  port: 8083

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/atlassync_cart
    username: atlassync
    password: atlassync
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  client:
    product-service:
      address: static://localhost:9082
      negotiation-type: plaintext
    session-service:
      address: static://localhost:9084
      negotiation-type: plaintext

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
